"""add_phase3_capability_flags

Revision ID: 28c6b758594a
Revises: 
Create Date: 2025-12-20 02:19:23.060910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c6b758594a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Unique device identifier'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-friendly device name'),
    sa.Column('management_ip', sa.String(length=45), nullable=False, comment='Management IP address (IPv4 or IPv6)'),
    sa.Column('management_port', sa.Integer(), nullable=False, comment='Management port (1-65535)'),
    sa.Column('environment', sa.String(length=32), nullable=False, comment='Environment: lab/staging/prod'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Current status: healthy/degraded/unreachable'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='Device tags (key-value pairs)'),
    sa.Column('allow_advanced_writes', sa.Boolean(), nullable=False, comment='Allow advanced tier write operations (Phase 2)'),
    sa.Column('allow_professional_workflows', sa.Boolean(), nullable=False, comment='Allow professional tier workflows (Phase 3+)'),
    sa.Column('allow_firewall_writes', sa.Boolean(), nullable=False, comment='Allow firewall filter/NAT rule writes (Phase 3)'),
    sa.Column('allow_routing_writes', sa.Boolean(), nullable=False, comment='Allow static route and routing policy writes (Phase 3)'),
    sa.Column('allow_wireless_writes', sa.Boolean(), nullable=False, comment='Allow wireless/RF configuration writes (Phase 3)'),
    sa.Column('allow_dhcp_writes', sa.Boolean(), nullable=False, comment='Allow DHCP server configuration writes (Phase 3)'),
    sa.Column('allow_bridge_writes', sa.Boolean(), nullable=False, comment='Allow bridge and VLAN configuration writes (Phase 3)'),
    sa.Column('routeros_version', sa.String(length=64), nullable=True, comment='RouterOS version string'),
    sa.Column('system_identity', sa.String(length=255), nullable=True, comment='RouterOS system identity'),
    sa.Column('hardware_model', sa.String(length=128), nullable=True, comment='Hardware model'),
    sa.Column('serial_number', sa.String(length=128), nullable=True, comment='Device serial number'),
    sa.Column('software_id', sa.String(length=128), nullable=True, comment='Software ID'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful contact timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_environment_status', 'devices', ['environment', 'status'], unique=False)
    op.create_index('idx_device_name', 'devices', ['name'], unique=False)
    op.create_index(op.f('ix_devices_environment'), 'devices', ['environment'], unique=False)
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False, comment='User sub who created plan'),
    sa.Column('tool_name', sa.String(length=128), nullable=False, comment='Tool that generated plan'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Status: draft/approved/applied/cancelled'),
    sa.Column('device_ids', sa.JSON(), nullable=False, comment='List of target device IDs'),
    sa.Column('summary', sa.Text(), nullable=False, comment='Human-readable plan summary'),
    sa.Column('changes', sa.JSON(), nullable=False, comment='Detailed change specifications'),
    sa.Column('approved_by', sa.String(length=255), nullable=True, comment='User sub who approved plan'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Approval timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plan_created_by', 'plans', ['created_by'], unique=False)
    op.create_index('idx_plan_status', 'plans', ['status'], unique=False)
    op.create_index(op.f('ix_plans_created_by'), 'plans', ['created_by'], unique=False)
    op.create_index(op.f('ix_plans_status'), 'plans', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Event timestamp'),
    sa.Column('user_sub', sa.String(length=255), nullable=False, comment='User subject from OIDC token'),
    sa.Column('user_email', sa.String(length=255), nullable=True, comment='User email'),
    sa.Column('user_role', sa.String(length=32), nullable=False, comment='User role at time of action'),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=True, comment='Device environment'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='Action type: WRITE/READ_SENSITIVE/AUTHZ_DENIED'),
    sa.Column('tool_name', sa.String(length=128), nullable=False, comment='MCP tool name'),
    sa.Column('tool_tier', sa.String(length=32), nullable=False, comment='Tool tier: fundamental/advanced/professional'),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False, comment='Result: SUCCESS/FAILURE'),
    sa.Column('meta', sa.JSON(), nullable=False, comment='Additional event metadata'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_result', 'audit_events', ['result'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_events', ['timestamp'], unique=False)
    op.create_index('idx_audit_tool', 'audit_events', ['tool_name'], unique=False)
    op.create_index('idx_audit_user_action', 'audit_events', ['user_sub', 'action'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_device_id'), 'audit_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_audit_events_environment'), 'audit_events', ['environment'], unique=False)
    op.create_index(op.f('ix_audit_events_job_id'), 'audit_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_audit_events_plan_id'), 'audit_events', ['plan_id'], unique=False)
    op.create_index(op.f('ix_audit_events_result'), 'audit_events', ['result'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_tool_name'), 'audit_events', ['tool_name'], unique=False)
    op.create_index(op.f('ix_audit_events_user_sub'), 'audit_events', ['user_sub'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('credential_type', sa.String(length=32), nullable=False, comment='Credential type: rest/ssh'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Username (stored in plaintext)'),
    sa.Column('encrypted_secret', sa.Text(), nullable=False, comment='Encrypted password/key'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Whether credential is active'),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True, comment='Last rotation timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credential_device_credential_type', 'credentials', ['device_id', 'credential_type'], unique=False)
    op.create_index(op.f('ix_credentials_device_id'), 'credentials', ['device_id'], unique=False)
    op.create_table('health_checks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Health check timestamp'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Status: healthy/warning/critical'),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('memory_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('memory_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if check failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_healthcheck_device_timestamp', 'health_checks', ['device_id', 'timestamp'], unique=False)
    op.create_index('idx_healthcheck_status', 'health_checks', ['status'], unique=False)
    op.create_index(op.f('ix_health_checks_device_id'), 'health_checks', ['device_id'], unique=False)
    op.create_index(op.f('ix_health_checks_timestamp'), 'health_checks', ['timestamp'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False, comment='Job type: APPLY_PLAN/HEALTH_CHECK/etc'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Status: pending/running/success/failed/cancelled'),
    sa.Column('device_ids', sa.JSON(), nullable=False, comment='Target device IDs'),
    sa.Column('attempts', sa.Integer(), nullable=False, comment='Number of attempts made'),
    sa.Column('max_attempts', sa.Integer(), nullable=False, comment='Maximum retry attempts'),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True, comment='Scheduled execution time'),
    sa.Column('result_summary', sa.Text(), nullable=True, comment='Job execution summary'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_status_next_run', 'jobs', ['status', 'next_run_at'], unique=False)
    op.create_index('idx_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_next_run_at'), 'jobs', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_jobs_plan_id'), 'jobs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False, comment='Snapshot type: config/dns_ntp/metrics/etc'),
    sa.Column('data', sa.LargeBinary(), nullable=False, comment='Compressed snapshot data'),
    sa.Column('meta', sa.JSON(), nullable=False, comment='Snapshot metadata (size, checksum, etc)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_device_timestamp', 'snapshots', ['device_id', 'timestamp'], unique=False)
    op.create_index('idx_snapshot_kind', 'snapshots', ['kind'], unique=False)
    op.create_index(op.f('ix_snapshots_device_id'), 'snapshots', ['device_id'], unique=False)
    op.create_index(op.f('ix_snapshots_timestamp'), 'snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_timestamp'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_device_id'), table_name='snapshots')
    op.drop_index('idx_snapshot_kind', table_name='snapshots')
    op.drop_index('idx_snapshot_device_timestamp', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_plan_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_next_run_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index('idx_job_type', table_name='jobs')
    op.drop_index('idx_job_status_next_run', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_health_checks_timestamp'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_device_id'), table_name='health_checks')
    op.drop_index('idx_healthcheck_status', table_name='health_checks')
    op.drop_index('idx_healthcheck_device_timestamp', table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index(op.f('ix_credentials_device_id'), table_name='credentials')
    op.drop_index('idx_credential_device_credential_type', table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_audit_events_user_sub'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tool_name'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_result'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_plan_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_job_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_environment'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_device_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('idx_audit_user_action', table_name='audit_events')
    op.drop_index('idx_audit_tool', table_name='audit_events')
    op.drop_index('idx_audit_timestamp', table_name='audit_events')
    op.drop_index('idx_audit_result', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_plans_status'), table_name='plans')
    op.drop_index(op.f('ix_plans_created_by'), table_name='plans')
    op.drop_index('idx_plan_status', table_name='plans')
    op.drop_index('idx_plan_created_by', table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_index(op.f('ix_devices_environment'), table_name='devices')
    op.drop_index('idx_device_name', table_name='devices')
    op.drop_index('idx_device_environment_status', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
