"""Add adaptive polling fields to Device

Revision ID: de268cf36ca1
Revises: 32
Create Date: 2026-01-08 02:53:27.048193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de268cf36ca1'
down_revision: Union[str, None] = '32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('critical', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='Critical device (30s base polling) vs non-critical (60s base polling) - Phase 4'))
    op.add_column('devices', sa.Column('health_status', sa.String(length=32), nullable=False, server_default=sa.text("'healthy'"), comment='Current health status: healthy/degraded/unreachable - Phase 4'))
    op.add_column('devices', sa.Column('consecutive_healthy_checks', sa.Integer(), nullable=False, server_default=sa.text('0'), comment='Count of consecutive healthy checks for interval adjustment - Phase 4'))
    op.add_column('devices', sa.Column('polling_interval_seconds', sa.Integer(), nullable=False, server_default=sa.text('60'), comment='Current adaptive polling interval in seconds - Phase 4'))
    op.add_column('devices', sa.Column('last_backoff_at', sa.DateTime(timezone=True), nullable=True, comment='Last exponential backoff timestamp for unreachable devices - Phase 4'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_backoff_at')
    op.drop_column('devices', 'polling_interval_seconds')
    op.drop_column('devices', 'consecutive_healthy_checks')
    op.drop_column('devices', 'health_status')
    op.drop_column('devices', 'critical')
    # ### end Alembic commands ###
